apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app-argo-config
  namespace: argocd
spec:
  project: itd-k8s
  source:
    repoURL: https://github.com/jayanthis952/argocd.git
    targetRevision: main
    path: argocd/kube_configs

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

