kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
        - name: ip-app
          image: harshajain/ip_app:latest
          ports:
            - containerPort: 8080
      VolumeMounts:
        -name: pvc-vol
        mountPath: /app/pvc-volumn
      Volumes:
        -name: pvc-vol
        persistentVolumeClaim:
          clainName:


